// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EpubVersion } from "./EpubVersion";
import type { Metadata } from "./Metadata";
import type { NavPoint } from "./NavPoint";
import type { Resource } from "./Resource";
import type { SpineItem } from "./SpineItem";

/**
 * A book opened in memory. A lightweight index: chapter bodies and binary
 * resources are never held here (invariant 3).
 */
export type Book = { id: string, metadata: Metadata, spine: Array<SpineItem>, nav: Array<NavPoint>, resources: Array<Resource>, 
/**
 * OS path of the opened file; `None` for unsaved new books.
 */
source: string | null, epub_version: EpubVersion, dirty: boolean, };
