// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentFormat } from "./ContentFormat";

/**
 * Chapter content, delivered on demand (never embedded in `Book`).
 */
export type ChapterContent = { resource: string, 
/**
 * See docs/contracts/content-roundtrip.md for when each format is used.
 */
format: ContentFormat, content: string, };
