// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidationIssue } from "./ValidationIssue";

export type CoreError = { "kind": "Io", message: string, } | { "kind": "NotAnEpub", message: string, } | { "kind": "MalformedPackage", message: string, } | { "kind": "ResourceNotFound", id: string, } | { "kind": "UnsupportedFeature", message: string, } | { "kind": "ValidationFailed", issues: Array<ValidationIssue>, } | { "kind": "ConversionLossy", detail: string, };
