// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Metadata = { title: string, authors: Array<string>, 
/**
 * BCP 47 language tag, e.g. "en".
 */
language: string, 
/**
 * dc:identifier (URN/UUID/ISBN).
 */
identifier: string, 
/**
 * dcterms:modified, ISO 8601 UTC.
 */
modified: string | null, description: string | null, publisher: string | null, cover_resource: string | null, };
