// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NavPoint = { label: string, 
/**
 * Resource path plus optional fragment; `None` for section headers.
 */
href: string | null, children: Array<NavPoint>, };
