// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Resource = { id: string, 
/**
 * Zip-internal path, normalized, relative to the archive root.
 */
path: string, 
/**
 * e.g. "application/xhtml+xml", "image/jpeg".
 */
media_type: string, 
/**
 * Uncompressed bytes.
 */
size: bigint, };
