// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpineItem = { id: string, 
/**
 * Must reference an XHTML content document.
 */
resource: string, 
/**
 * Non-linear items exist but aren't in the reading flow.
 */
linear: boolean, };
