// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Severity } from "./Severity";

export type ValidationIssue = { severity: Severity, location: string | null, message: string, };
