//! Book model assembly and the in-memory session of open books.
//!
//! `open_book` wires the container (M0.2), OPF (M0.3), and nav (M0.4) layers
//! into the `Book` index eagerly; chapter bodies stay in the zip and are
//! decompressed on demand via `read_chapter` / `read_resource` (ADR-0002,
//! domain-model.md invariant 3).

use std::collections::{HashMap, HashSet};
use std::fs::File;
use std::io::Write;
use std::path::{Path, PathBuf};

use quick_xml::events::Event as XmlEvent;
use quick_xml::name::QName;
use quick_xml::Reader;
use zip::write::SimpleFileOptions;
use zip::CompressionMethod;

use crate::container::OcfContainer;
use crate::error::{CoreError, CoreResult, Severity, ValidationIssue};
use crate::model::{
    Book, BookId, ChapterContent, ContentFormat, EpubVersion, Metadata, NavPoint, Resource,
    ResourceId, SpineItem, SpineItemId,
};
use crate::{nav, opf, roundtrip, writer};

const XHTML_MEDIA_TYPE: &str = "application/xhtml+xml";
const MIMETYPE_PATH: &str = "mimetype";
const EPUB_MIMETYPE: &str = "application/epub+zip";
const CONTAINER_XML_PATH: &str = "META-INF/container.xml";
const DEFAULT_PACKAGE_PATH: &str = "OEBPS/content.opf";

/// One open book: the lightweight model, its backing container (if it has
/// one), and an in-memory overlay of zip entries. The overlay takes
/// precedence over the container on reads; books from `create_book` live
/// entirely in the overlay (`container: None`).
struct OpenBook {
    book: Book,
    container: Option<OcfContainer<File>>,
    /// Zip-internal path → bytes; overrides the container.
    overlay: HashMap<String, Vec<u8>>,
    /// Zip-internal paths deleted by mutations: hidden on reads and skipped
    /// by `save_book`'s raw copy even when the container still holds them.
    removed: HashSet<String>,
    /// Zip-internal path of the package document (OPF).
    package_path: String,
    /// Manifest item carrying `properties="nav"`, if any.
    nav_resource: Option<ResourceId>,
    /// NCX manifest item (spine `toc` idref), if any.
    ncx_resource: Option<ResourceId>,
    /// True for books from `create_book`: the "titlepage" resource is
    /// generated and gets regenerated by `update_metadata`.
    generated_title_page: bool,
}

impl OpenBook {
    /// Uncompressed bytes of one entry: overlay first, then the container.
    fn read_entry(&mut self, path: &str) -> CoreResult<Vec<u8>> {
        if let Some(bytes) = self.overlay.get(path) {
            return Ok(bytes.clone());
        }
        if self.removed.contains(path) {
            return Err(CoreError::ResourceNotFound { id: path.into() });
        }
        match &mut self.container {
            Some(container) => container.read_entry(path),
            None => Err(CoreError::ResourceNotFound { id: path.into() }),
        }
    }

    /// Whether the bytes for one entry are actually available.
    fn has_entry(&mut self, path: &str) -> bool {
        if self.overlay.contains_key(path) {
            return true;
        }
        if self.removed.contains(path) {
            return false;
        }
        match &mut self.container {
            Some(container) => container.entry_size(path).is_ok(),
            None => false,
        }
    }
}

/// In-memory registry of open books, keyed by `BookId` (core-api.md).
#[derive(Default)]
pub struct Session {
    books: HashMap<BookId, OpenBook>,
    next_id: u64,
}

impl Session {
    pub fn new() -> Self {
        Self::default()
    }

    /// Open an EPUB from an OS path: container → OPF → nav, sizes filled,
    /// invariants enforced. Chapter bodies are not read.
    pub fn open_book(&mut self, path: impl AsRef<Path>) -> CoreResult<Book> {
        let path = path.as_ref();
        let mut container = OcfContainer::open_path(path)?;

        let package_path = container.package_path().to_owned();
        let opf_bytes = container.read_entry(&package_path)?;
        let package = opf::parse_opf(&opf_bytes, &package_path)?;

        let mut resources = package.resources;
        fill_sizes(&mut resources, &mut container);

        let nav = parse_nav(
            &mut container,
            &resources,
            package.nav_resource.as_deref(),
            package.ncx_resource.as_deref(),
        )?;

        // Invariants (domain-model.md): spine idrefs resolve (also checked by
        // the OPF parser) and every nav href points at a manifest resource.
        for item in &package.spine {
            if !resources.iter().any(|r| r.id == item.resource) {
                return Err(CoreError::MalformedPackage {
                    message: format!("spine item {:?} has no manifest resource", item.resource),
                });
            }
        }
        nav::validate_nav_targets(&nav, &resources)?;

        self.next_id += 1;
        let id: BookId = format!("book-{}", self.next_id);
        let book = Book {
            id: id.clone(),
            metadata: package.metadata,
            spine: package.spine,
            nav,
            resources,
            source: Some(path.to_string_lossy().into_owned()),
            epub_version: package.version,
            dirty: false,
        };
        self.books.insert(
            id,
            OpenBook {
                book: book.clone(),
                container: Some(container),
                overlay: HashMap::new(),
                removed: HashSet::new(),
                package_path,
                nav_resource: package.nav_resource,
                ncx_resource: package.ncx_resource,
                generated_title_page: false,
            },
        );
        Ok(book)
    }

    /// Create a new in-memory EPUB 3 book with no backing file: a generated
    /// title page, a nav document listing it, and a consistent spine
    /// (core-api.md). Everything lives in the overlay until `save_book`.
    pub fn create_book(&mut self, metadata: Metadata) -> Book {
        let mut metadata = metadata;
        if metadata.identifier.is_empty() {
            metadata.identifier = writer::generate_identifier();
        }
        if metadata.language.is_empty() {
            metadata.language = "en".to_owned();
        }

        let title_page_path = "OEBPS/titlepage.xhtml".to_owned();
        let nav_path = "OEBPS/nav.xhtml".to_owned();
        let title_page = writer::write_title_page_xhtml(&metadata);
        let nav_label = if metadata.title.is_empty() {
            "Title Page".to_owned()
        } else {
            metadata.title.clone()
        };
        let nav_points = vec![NavPoint {
            label: nav_label,
            href: Some(title_page_path.clone()),
            children: Vec::new(),
        }];
        let nav_doc = writer::write_nav_xhtml(&metadata, &nav_points, &nav_path);

        let mut overlay = HashMap::new();
        overlay.insert(
            CONTAINER_XML_PATH.to_owned(),
            writer::write_container_xml(DEFAULT_PACKAGE_PATH).into_bytes(),
        );
        overlay.insert(title_page_path.clone(), title_page.into_bytes());
        overlay.insert(nav_path.clone(), nav_doc.into_bytes());

        let resources = vec![
            Resource {
                id: "titlepage".to_owned(),
                path: title_page_path.clone(),
                media_type: XHTML_MEDIA_TYPE.to_owned(),
                size: overlay[&title_page_path].len() as u64,
            },
            Resource {
                id: "nav".to_owned(),
                path: nav_path.clone(),
                media_type: XHTML_MEDIA_TYPE.to_owned(),
                size: overlay[&nav_path].len() as u64,
            },
        ];

        self.next_id += 1;
        let id: BookId = format!("book-{}", self.next_id);
        let book = Book {
            id: id.clone(),
            metadata,
            spine: vec![SpineItem {
                id: "spine-0".to_owned(),
                resource: "titlepage".to_owned(),
                linear: true,
            }],
            nav: nav_points,
            resources,
            source: None,
            epub_version: EpubVersion::V3,
            dirty: true,
        };
        self.books.insert(
            id,
            OpenBook {
                book: book.clone(),
                container: None,
                overlay,
                removed: HashSet::new(),
                package_path: DEFAULT_PACKAGE_PATH.to_owned(),
                nav_resource: Some("nav".to_owned()),
                ncx_resource: None,
                generated_title_page: true,
            },
        );
        book
    }

    /// Atomic incremental save (ADR-0002): serialize to a temp file next to
    /// the target, then rename over it. `mimetype` is written first and
    /// stored; the OPF is regenerated from the model with a refreshed
    /// `dcterms:modified`; overlay entries are written from memory; every
    /// other entry is raw-copied from the source container without
    /// re-encoding. `path` is required when the book has no source (save-as).
    pub fn save_book(&mut self, book_id: &str, path: Option<String>) -> CoreResult<Book> {
        let open = self.open_mut(book_id)?;
        let target: PathBuf = match path.or_else(|| open.book.source.clone()) {
            Some(p) => PathBuf::from(p),
            None => {
                return Err(CoreError::Io {
                    message: "save_book: book has no source file; a path is required (save-as)"
                        .into(),
                })
            }
        };

        let modified = writer::now_iso8601();
        let opf_bytes = writer::write_opf(
            &open.book,
            open.nav_resource.as_deref(),
            open.ncx_resource.as_deref(),
            &open.package_path,
            &modified,
        )
        .into_bytes();

        let dir = match target.parent() {
            Some(d) if !d.as_os_str().is_empty() => d.to_path_buf(),
            _ => PathBuf::from("."),
        };
        let file_name =
            target
                .file_name()
                .and_then(|n| n.to_str())
                .ok_or_else(|| CoreError::Io {
                    message: format!("save_book: invalid target path {}", target.display()),
                })?;
        let temp_path = dir.join(format!(".{file_name}.tmp-{}", std::process::id()));

        let result = write_epub_zip(open, &temp_path, &opf_bytes);
        if let Err(err) = result {
            let _ = std::fs::remove_file(&temp_path);
            return Err(err);
        }
        if let Err(e) = std::fs::rename(&temp_path, &target) {
            let _ = std::fs::remove_file(&temp_path);
            return Err(CoreError::Io {
                message: format!("cannot move saved file into {}: {e}", target.display()),
            });
        }

        open.book.source = Some(target.to_string_lossy().into_owned());
        open.book.dirty = false;
        open.book.metadata.modified = Some(modified);
        // Re-point the container at the saved file so later saves stay
        // incremental (and save-as leaves the old file alone).
        open.container = Some(OcfContainer::open_path(&target)?);
        Ok(open.book.clone())
    }

    /// Current model snapshot.
    pub fn get_book(&self, book_id: &str) -> CoreResult<Book> {
        self.open(book_id).map(|ob| ob.book.clone())
    }

    /// Decompress one chapter on demand. `prefer: Markdown` converts the
    /// body per content-roundtrip.md, falling back to `format: Xhtml` with
    /// the full document when the content is outside the supported subset —
    /// lossy conversion is never an error here, it just means source mode.
    /// `prefer: Xhtml` returns the stored document as-is.
    pub fn read_chapter(
        &mut self,
        book_id: &str,
        resource_id: &str,
        prefer: ContentFormat,
    ) -> CoreResult<ChapterContent> {
        let open = self.open_mut(book_id)?;
        let resource = find_resource(&open.book, resource_id)?;
        if resource.media_type != XHTML_MEDIA_TYPE {
            return Err(CoreError::UnsupportedFeature {
                message: format!(
                    "resource {resource_id:?} is {:?}, not a chapter ({XHTML_MEDIA_TYPE})",
                    resource.media_type
                ),
            });
        }
        let path = resource.path.clone();
        let bytes = open.read_entry(&path)?;
        let content = String::from_utf8(bytes).map_err(|e| CoreError::MalformedPackage {
            message: format!("chapter {path} is not valid UTF-8: {e}"),
        })?;
        if prefer == ContentFormat::Markdown {
            if let Some(span) = body_span(&content) {
                match roundtrip::xhtml_to_markdown(&content[span]) {
                    Ok(markdown) => {
                        return Ok(ChapterContent {
                            resource: resource_id.to_owned(),
                            format: ContentFormat::Markdown,
                            content: markdown,
                        })
                    }
                    // Out-of-subset content → source mode (format: Xhtml).
                    Err(CoreError::ConversionLossy { .. }) => {}
                    Err(other) => return Err(other),
                }
            }
        }
        Ok(ChapterContent {
            resource: resource_id.to_owned(),
            format: ContentFormat::Xhtml,
            content,
        })
    }

    /// Raw bytes of any manifest resource (images, CSS, fonts, …).
    pub fn read_resource(&mut self, book_id: &str, resource_id: &str) -> CoreResult<Vec<u8>> {
        let open = self.open_mut(book_id)?;
        let path = find_resource(&open.book, resource_id)?.path.clone();
        open.read_entry(&path)
    }

    /// Replace one chapter's content (core-api.md). Markdown is converted to
    /// XHTML and spliced into the chapter's existing document frame — the
    /// `<head>` is preserved verbatim per content-roundtrip.md; chapters
    /// without a usable frame get a minimal generated one. XHTML is stored
    /// as-is. Bytes land in the session overlay until `save_book`.
    pub fn write_chapter(
        &mut self,
        book_id: &str,
        resource_id: &str,
        content: ChapterContent,
    ) -> CoreResult<Book> {
        let open = self.open_mut(book_id)?;
        ensure_editable(&open.book)?;
        let resource = find_resource(&open.book, resource_id)?;
        if resource.media_type != XHTML_MEDIA_TYPE {
            return Err(CoreError::UnsupportedFeature {
                message: format!(
                    "resource {resource_id:?} is {:?}, not a chapter ({XHTML_MEDIA_TYPE})",
                    resource.media_type
                ),
            });
        }
        let path = resource.path.clone();
        let doc = match content.format {
            ContentFormat::Xhtml => content.content,
            ContentFormat::Markdown => {
                let body = roundtrip::markdown_to_xhtml(&content.content);
                let existing = open
                    .read_entry(&path)
                    .ok()
                    .and_then(|bytes| String::from_utf8(bytes).ok());
                let framed = existing
                    .as_deref()
                    .and_then(|doc| body_span(doc).map(|span| splice_body(doc, span, &body)));
                match framed {
                    Some(doc) => doc,
                    None => {
                        let title = nav_label_for_path(&open.book.nav, &path)
                            .unwrap_or("Chapter")
                            .to_owned();
                        writer::write_chapter_xhtml(&title, &open.book.metadata.language, &body)
                    }
                }
            }
        };
        let bytes = doc.into_bytes();
        let size = bytes.len() as u64;
        open.overlay.insert(path, bytes);
        if let Some(r) = open.book.resources.iter_mut().find(|r| r.id == resource_id) {
            r.size = size;
        }
        open.book.dirty = true;
        Ok(open.book.clone())
    }

    /// Add a binary resource (M3.3: images) to the manifest and the session
    /// overlay. The zip-internal path is derived from `path_hint`'s file name
    /// under `<package dir>/images/`, suffixed `-2`, `-3`, … until it collides
    /// with nothing in the manifest; the manifest id is derived the same way.
    /// Bytes stay in the overlay until `save_book`.
    pub fn add_resource(
        &mut self,
        book_id: &str,
        path_hint: &str,
        media_type: &str,
        bytes: Vec<u8>,
    ) -> CoreResult<Book> {
        let open = self.open_mut(book_id)?;
        ensure_editable(&open.book)?;

        let (stem, ext) = split_hint(path_hint);
        let stem = sanitize_stem(&stem);
        let dir = parent_dir(&open.package_path);
        let images_dir = if dir.is_empty() {
            "images".to_owned()
        } else {
            format!("{dir}/images")
        };
        let (resource_id, path) = unique_asset_slot(&open.book, &images_dir, &stem, ext.as_deref());

        open.book.resources.push(Resource {
            id: resource_id,
            path: path.clone(),
            media_type: media_type.to_owned(),
            size: bytes.len() as u64,
        });
        open.overlay.insert(path.clone(), bytes);
        open.removed.remove(&path);
        open.book.dirty = true;
        Ok(open.book.clone())
    }

    /// Replace the book's metadata. Regenerates the generated title page (and
    /// its nav label) for books born from `create_book`.
    pub fn update_metadata(&mut self, book_id: &str, metadata: Metadata) -> CoreResult<Book> {
        let open = self.open_mut(book_id)?;
        ensure_editable(&open.book)?;
        open.book.metadata = metadata;
        if open.generated_title_page {
            if let Some(resource) = open.book.resources.iter().find(|r| r.id == "titlepage") {
                let path = resource.path.clone();
                let bytes = writer::write_title_page_xhtml(&open.book.metadata).into_bytes();
                let size = bytes.len() as u64;
                open.overlay.insert(path.clone(), bytes);
                if let Some(r) = open.book.resources.iter_mut().find(|r| r.id == "titlepage") {
                    r.size = size;
                }
                let label = if open.book.metadata.title.is_empty() {
                    "Title Page".to_owned()
                } else {
                    open.book.metadata.title.clone()
                };
                for point in &mut open.book.nav {
                    if point.href.as_deref().map(strip_fragment) == Some(path.as_str()) {
                        point.label = label.clone();
                    }
                }
            }
            regenerate_nav(open);
        }
        open.book.dirty = true;
        Ok(open.book.clone())
    }

    /// Create a new empty chapter: XHTML resource (unique id + path),
    /// manifest entry, spine entry (after `after`, or at the end), and a
    /// top-level nav entry positioned consistently with the spine.
    pub fn add_chapter(
        &mut self,
        book_id: &str,
        title: &str,
        after: Option<&str>,
    ) -> CoreResult<Book> {
        let open = self.open_mut(book_id)?;
        ensure_editable(&open.book)?;
        let spine_pos = match after {
            Some(after_id) => match open.book.spine.iter().position(|s| s.id == after_id) {
                Some(i) => i + 1,
                None => {
                    return Err(CoreError::ResourceNotFound {
                        id: after_id.to_owned(),
                    })
                }
            },
            None => open.book.spine.len(),
        };

        let dir = parent_dir(&open.package_path);
        let (resource_id, path) = unique_chapter_slot(&open.book, dir);
        let body = format!("  <h1>{}</h1>\n", writer::escape_xml(title));
        let bytes =
            writer::write_chapter_xhtml(title, &open.book.metadata.language, &body).into_bytes();
        open.book.resources.push(Resource {
            id: resource_id.clone(),
            path: path.clone(),
            media_type: XHTML_MEDIA_TYPE.to_owned(),
            size: bytes.len() as u64,
        });
        open.overlay.insert(path.clone(), bytes);
        open.removed.remove(&path);

        let spine_id = unique_spine_id(&open.book);
        open.book.spine.insert(
            spine_pos,
            SpineItem {
                id: spine_id,
                resource: resource_id,
                linear: true,
            },
        );

        let nav_pos = nav_insert_index(&open.book, spine_pos);
        open.book.nav.insert(
            nav_pos,
            NavPoint {
                label: title.to_owned(),
                href: Some(path),
                children: Vec::new(),
            },
        );

        regenerate_nav(open);
        open.book.dirty = true;
        Ok(open.book.clone())
    }

    /// Remove one spine entry, every nav entry pointing at its resource
    /// (children are dropped with their parent), and — when nothing else
    /// references it — the resource itself from manifest and storage.
    pub fn remove_chapter(&mut self, book_id: &str, spine_item_id: &str) -> CoreResult<Book> {
        let open = self.open_mut(book_id)?;
        ensure_editable(&open.book)?;
        let index = open
            .book
            .spine
            .iter()
            .position(|s| s.id == spine_item_id)
            .ok_or_else(|| CoreError::ResourceNotFound {
                id: spine_item_id.to_owned(),
            })?;
        let resource_id = open.book.spine.remove(index).resource;

        if let Some(path) = open
            .book
            .resources
            .iter()
            .find(|r| r.id == resource_id)
            .map(|r| r.path.clone())
        {
            remove_nav_entries(&mut open.book.nav, &path);
            let still_in_spine = open.book.spine.iter().any(|s| s.resource == resource_id);
            let still_in_nav = nav_references(&open.book.nav, &path);
            let is_nav_doc = open.nav_resource.as_deref() == Some(resource_id.as_str())
                || open.ncx_resource.as_deref() == Some(resource_id.as_str());
            if !still_in_spine && !still_in_nav && !is_nav_doc {
                open.book.resources.retain(|r| r.id != resource_id);
                open.overlay.remove(&path);
                if open.container.is_some() {
                    open.removed.insert(path);
                }
            }
        }

        regenerate_nav(open);
        open.book.dirty = true;
        Ok(open.book.clone())
    }

    /// Reorder the spine. `order` must be an exact permutation of the
    /// current spine item ids. Top-level nav entries that point at spine
    /// resources are reordered to follow; other nav entries keep their slots.
    pub fn reorder_spine(&mut self, book_id: &str, order: &[SpineItemId]) -> CoreResult<Book> {
        let open = self.open_mut(book_id)?;
        ensure_editable(&open.book)?;

        let mut current: Vec<&str> = open.book.spine.iter().map(|s| s.id.as_str()).collect();
        let mut requested: Vec<&str> = order.iter().map(|s| s.as_str()).collect();
        current.sort_unstable();
        requested.sort_unstable();
        if current != requested {
            return Err(CoreError::MalformedPackage {
                message: "reorder_spine: order must be an exact permutation of the current spine"
                    .into(),
            });
        }

        let mut by_id: HashMap<String, SpineItem> = open
            .book
            .spine
            .drain(..)
            .map(|item| (item.id.clone(), item))
            .collect();
        open.book.spine = order
            .iter()
            .map(|id| by_id.remove(id).expect("permutation checked above"))
            .collect();

        // Resource path → position in the new spine (first occurrence).
        let mut spine_pos: HashMap<String, usize> = HashMap::new();
        for (i, item) in open.book.spine.iter().enumerate() {
            if let Some(r) = open.book.resources.iter().find(|r| r.id == item.resource) {
                spine_pos.entry(r.path.clone()).or_insert(i);
            }
        }
        let slots: Vec<usize> = open
            .book
            .nav
            .iter()
            .enumerate()
            .filter(|(_, point)| {
                point
                    .href
                    .as_deref()
                    .map(strip_fragment)
                    .is_some_and(|href| spine_pos.contains_key(href))
            })
            .map(|(i, _)| i)
            .collect();
        let mut chapters: Vec<NavPoint> = slots.iter().map(|&i| open.book.nav[i].clone()).collect();
        chapters.sort_by_key(|point| {
            spine_pos[strip_fragment(point.href.as_deref().expect("filtered on href"))]
        });
        for (&slot, point) in slots.iter().zip(chapters) {
            open.book.nav[slot] = point;
        }

        regenerate_nav(open);
        open.book.dirty = true;
        Ok(open.book.clone())
    }

    /// Native validation subset (ADR-0003): required metadata, spine/nav/
    /// manifest consistency, resource bytes present, XML well-formedness of
    /// XHTML documents, duplicate manifest ids/paths. Findings come back as
    /// issues, never as `Err`.
    pub fn validate(&mut self, book_id: &str) -> CoreResult<Vec<ValidationIssue>> {
        let open = self.open_mut(book_id)?;
        let mut issues = Vec::new();
        let opf_path = open.package_path.clone();
        let opf_loc = move || Some(opf_path.clone());
        let error = |location: Option<String>, message: String| ValidationIssue {
            severity: Severity::Error,
            location,
            message,
        };

        for (value, name) in [
            (&open.book.metadata.title, "dc:title"),
            (&open.book.metadata.identifier, "dc:identifier"),
            (&open.book.metadata.language, "dc:language"),
        ] {
            if value.is_empty() {
                issues.push(error(
                    opf_loc(),
                    format!("missing required metadata: {name}"),
                ));
            }
        }

        if open.book.spine.is_empty() {
            issues.push(error(opf_loc(), "spine is empty".to_owned()));
        }
        for item in &open.book.spine {
            match open.book.resources.iter().find(|r| r.id == item.resource) {
                None => issues.push(error(
                    opf_loc(),
                    format!(
                        "spine item {:?} references missing manifest resource {:?}",
                        item.id, item.resource
                    ),
                )),
                Some(r) if r.media_type != XHTML_MEDIA_TYPE => issues.push(error(
                    opf_loc(),
                    format!(
                        "spine item {:?} references {:?} with media type {:?}, expected {XHTML_MEDIA_TYPE}",
                        item.id, item.resource, r.media_type
                    ),
                )),
                Some(_) => {}
            }
        }

        let mut nav_targets = Vec::new();
        collect_nav_targets(&open.book.nav, &mut nav_targets);
        for (label, href) in nav_targets {
            let path = strip_fragment(&href);
            if !open.book.resources.iter().any(|r| r.path == path) {
                issues.push(error(
                    None,
                    format!("nav entry {label:?} targets {href:?}, which is not in the manifest"),
                ));
            }
        }

        let mut seen_ids: HashSet<&str> = HashSet::new();
        let mut seen_paths: HashSet<&str> = HashSet::new();
        for r in &open.book.resources {
            if !seen_ids.insert(&r.id) {
                issues.push(error(
                    opf_loc(),
                    format!("duplicate manifest id {:?}", r.id),
                ));
            }
            if !seen_paths.insert(&r.path) {
                issues.push(error(
                    opf_loc(),
                    format!("duplicate manifest path {:?}", r.path),
                ));
            }
        }

        let entries: Vec<(String, String, bool)> = open
            .book
            .resources
            .iter()
            .map(|r| {
                (
                    r.id.clone(),
                    r.path.clone(),
                    r.media_type == XHTML_MEDIA_TYPE,
                )
            })
            .collect();
        for (id, path, is_xhtml) in entries {
            if !open.has_entry(&path) {
                issues.push(error(
                    Some(path.clone()),
                    format!("resource {id:?} has no bytes in the archive or session"),
                ));
                continue;
            }
            if is_xhtml {
                match open.read_entry(&path) {
                    Ok(bytes) => {
                        if let Err(detail) = xml_well_formed(&bytes) {
                            issues.push(error(
                                Some(path.clone()),
                                format!("resource {id:?} is not well-formed XML: {detail}"),
                            ));
                        }
                    }
                    Err(e) => issues.push(error(
                        Some(path.clone()),
                        format!("resource {id:?} could not be read: {e}"),
                    )),
                }
            }
        }

        Ok(issues)
    }

    /// Drop session state for one book.
    pub fn close_book(&mut self, book_id: &str) -> CoreResult<()> {
        self.books
            .remove(book_id)
            .map(|_| ())
            .ok_or_else(|| CoreError::ResourceNotFound {
                id: book_id.to_owned(),
            })
    }

    fn open(&self, book_id: &str) -> CoreResult<&OpenBook> {
        self.books
            .get(book_id)
            .ok_or_else(|| CoreError::ResourceNotFound {
                id: book_id.to_owned(),
            })
    }

    fn open_mut(&mut self, book_id: &str) -> CoreResult<&mut OpenBook> {
        self.books
            .get_mut(book_id)
            .ok_or_else(|| CoreError::ResourceNotFound {
                id: book_id.to_owned(),
            })
    }
}

/// Assemble the EPUB zip at `temp_path`: stored mimetype first, regenerated
/// OPF, overlay entries from memory, everything else raw-copied.
fn write_epub_zip(open: &mut OpenBook, temp_path: &Path, opf_bytes: &[u8]) -> CoreResult<()> {
    let io_err = |what: &str, e: &dyn std::fmt::Display| CoreError::Io {
        message: format!("save_book: {what}: {e}"),
    };

    let file = File::create(temp_path).map_err(|e| CoreError::Io {
        message: format!("cannot create temp file {}: {e}", temp_path.display()),
    })?;
    let mut zip = zip::ZipWriter::new(file);
    let deflated = SimpleFileOptions::default().compression_method(CompressionMethod::Deflated);

    // OCF 4.2: mimetype first, uncompressed.
    zip.start_file(
        MIMETYPE_PATH,
        SimpleFileOptions::default().compression_method(CompressionMethod::Stored),
    )
    .map_err(|e| io_err("writing mimetype", &e))?;
    zip.write_all(EPUB_MIMETYPE.as_bytes())
        .map_err(|e| io_err("writing mimetype", &e))?;

    zip.start_file(open.package_path.as_str(), deflated)
        .map_err(|e| io_err("writing package document", &e))?;
    zip.write_all(opf_bytes)
        .map_err(|e| io_err("writing package document", &e))?;

    let mut overlay_paths: Vec<&String> = open
        .overlay
        .keys()
        .filter(|p| p.as_str() != MIMETYPE_PATH && **p != open.package_path)
        .collect();
    overlay_paths.sort();
    for path in overlay_paths {
        zip.start_file(path.as_str(), deflated)
            .map_err(|e| io_err(&format!("writing {path}"), &e))?;
        zip.write_all(&open.overlay[path])
            .map_err(|e| io_err(&format!("writing {path}"), &e))?;
    }

    if let Some(container) = &mut open.container {
        let overlay = &open.overlay;
        let removed = &open.removed;
        let package_path = open.package_path.as_str();
        container.raw_copy_entries(&mut zip, |name| {
            name == MIMETYPE_PATH
                || name == package_path
                || overlay.contains_key(name)
                || removed.contains(name)
        })?;
    }

    zip.finish().map_err(|e| io_err("finalizing archive", &e))?;
    Ok(())
}

fn find_resource<'b>(book: &'b Book, resource_id: &str) -> CoreResult<&'b Resource> {
    book.resources
        .iter()
        .find(|r| r.id == resource_id)
        .ok_or_else(|| CoreError::ResourceNotFound {
            id: resource_id.to_owned(),
        })
}

/// Mutations target EPUB 3; EPUB 2 books are opened read-only (ADR-0003).
fn ensure_editable(book: &Book) -> CoreResult<()> {
    if book.epub_version == EpubVersion::V2 {
        return Err(CoreError::UnsupportedFeature {
            message: "EPUB 2 books are read-only (ADR-0003)".into(),
        });
    }
    Ok(())
}

/// Regenerate the nav document from the model's nav tree into the overlay so
/// saves reflect structural changes. Books without a nav resource get one
/// created next to the package document.
fn regenerate_nav(open: &mut OpenBook) {
    let nav_id = match &open.nav_resource {
        Some(id) => id.clone(),
        None => {
            let dir = parent_dir(&open.package_path);
            let path = if dir.is_empty() {
                "nav.xhtml".to_owned()
            } else {
                format!("{dir}/nav.xhtml")
            };
            let id = unique_resource_id(&open.book, "nav");
            open.book.resources.push(Resource {
                id: id.clone(),
                path,
                media_type: XHTML_MEDIA_TYPE.to_owned(),
                size: 0,
            });
            open.nav_resource = Some(id.clone());
            id
        }
    };
    let Some(path) = open
        .book
        .resources
        .iter()
        .find(|r| r.id == nav_id)
        .map(|r| r.path.clone())
    else {
        return;
    };
    let bytes = writer::write_nav_xhtml(&open.book.metadata, &open.book.nav, &path).into_bytes();
    let size = bytes.len() as u64;
    open.overlay.insert(path, bytes);
    if let Some(r) = open.book.resources.iter_mut().find(|r| r.id == nav_id) {
        r.size = size;
    }
}

/// Byte range of the `<body>` element's inner content within `doc`, or
/// `None` when the document has no well-formed `<body>`.
fn body_span(doc: &str) -> Option<std::ops::Range<usize>> {
    let mut reader = Reader::from_str(doc);
    loop {
        match reader.read_event() {
            Ok(XmlEvent::Start(e)) if e.local_name().as_ref() == "body" => {
                let name = e.name().as_ref().to_owned();
                let span = reader.read_to_end(QName(&name)).ok()?;
                return Some(span.start as usize..span.end as usize);
            }
            Ok(XmlEvent::Eof) | Err(_) => return None,
            Ok(_) => {}
        }
    }
}

/// Replace the `<body>` inner content of `doc` (span from [`body_span`])
/// with a fresh XHTML fragment, preserving the frame verbatim. Declares the
/// `epub:` namespace on `<html>` if the new body needs it and it is missing.
fn splice_body(doc: &str, span: std::ops::Range<usize>, body: &str) -> String {
    let mut out = String::with_capacity(doc.len() + body.len());
    out.push_str(&doc[..span.start]);
    out.push('\n');
    out.push_str(body);
    if !body.is_empty() && !body.ends_with('\n') {
        out.push('\n');
    }
    out.push_str(&doc[span.end..]);
    if body.contains("epub:") && !out.contains("xmlns:epub") {
        if let Some(i) = out.find("<html") {
            out.insert_str(
                i + "<html".len(),
                r#" xmlns:epub="http://www.idpf.org/2007/ops""#,
            );
        }
    }
    out
}

/// Zip path without an optional `#fragment` suffix.
fn strip_fragment(href: &str) -> &str {
    href.split_once('#').map_or(href, |(path, _)| path)
}

fn parent_dir(path: &str) -> &str {
    match path.rfind('/') {
        Some(i) => &path[..i],
        None => "",
    }
}

/// Label of the first nav entry (depth-first) targeting `path`.
fn nav_label_for_path<'n>(nav: &'n [NavPoint], path: &str) -> Option<&'n str> {
    for point in nav {
        if point.href.as_deref().map(strip_fragment) == Some(path) {
            return Some(&point.label);
        }
        if let Some(label) = nav_label_for_path(&point.children, path) {
            return Some(label);
        }
    }
    None
}

/// Drop every nav entry (recursively) targeting `path`, children included.
fn remove_nav_entries(nav: &mut Vec<NavPoint>, path: &str) {
    nav.retain(|point| point.href.as_deref().map(strip_fragment) != Some(path));
    for point in nav {
        remove_nav_entries(&mut point.children, path);
    }
}

fn nav_references(nav: &[NavPoint], path: &str) -> bool {
    nav.iter().any(|point| {
        point.href.as_deref().map(strip_fragment) == Some(path)
            || nav_references(&point.children, path)
    })
}

/// Collect `(label, href)` for every nav entry that has a target.
fn collect_nav_targets(nav: &[NavPoint], out: &mut Vec<(String, String)>) {
    for point in nav {
        if let Some(href) = &point.href {
            out.push((point.label.clone(), href.clone()));
        }
        collect_nav_targets(&point.children, out);
    }
}

/// First unused `chapter-N` manifest id + `dir/chapter-N.xhtml` path pair.
fn unique_chapter_slot(book: &Book, dir: &str) -> (String, String) {
    let mut n = 1usize;
    loop {
        let id = format!("chapter-{n}");
        let path = if dir.is_empty() {
            format!("chapter-{n}.xhtml")
        } else {
            format!("{dir}/chapter-{n}.xhtml")
        };
        if !book.resources.iter().any(|r| r.id == id || r.path == path) {
            return (id, path);
        }
        n += 1;
    }
}

/// File-name stem and lowercased extension of a path hint (OS path or bare
/// file name; both `/` and `\` separators are understood).
fn split_hint(path_hint: &str) -> (String, Option<String>) {
    let file_name = path_hint.rsplit(['/', '\\']).next().unwrap_or(path_hint);
    match file_name.rsplit_once('.') {
        Some((stem, ext)) if !stem.is_empty() && !ext.is_empty() => {
            (stem.to_owned(), Some(ext.to_ascii_lowercase()))
        }
        _ => (file_name.to_owned(), None),
    }
}

/// Zip-path-safe stem: Unicode alphanumerics, `-`, and `_` pass through
/// (UTF-8 safe); everything else collapses to single dashes.
fn sanitize_stem(stem: &str) -> String {
    let mut out = String::with_capacity(stem.len());
    for c in stem.chars() {
        if c.is_alphanumeric() || c == '-' || c == '_' {
            out.push(c);
        } else if !out.ends_with('-') {
            out.push('-');
        }
    }
    let out = out.trim_matches('-').to_owned();
    if out.is_empty() {
        "resource".to_owned()
    } else {
        out
    }
}

/// First collision-free `(manifest id, zip path)` pair for an asset named
/// after `stem` in `dir`: `stem[.ext]`, then `stem-2[.ext]`, `stem-3[.ext]`, …
fn unique_asset_slot(book: &Book, dir: &str, stem: &str, ext: Option<&str>) -> (String, String) {
    let mut n = 1usize;
    loop {
        let candidate = if n == 1 {
            stem.to_owned()
        } else {
            format!("{stem}-{n}")
        };
        let file_name = match ext {
            Some(ext) => format!("{candidate}.{ext}"),
            None => candidate.clone(),
        };
        let path = if dir.is_empty() {
            file_name
        } else {
            format!("{dir}/{file_name}")
        };
        if !book
            .resources
            .iter()
            .any(|r| r.id == candidate || r.path == path)
        {
            return (candidate, path);
        }
        n += 1;
    }
}

/// `base`, or the first unused `base-N`, as a manifest id.
fn unique_resource_id(book: &Book, base: &str) -> String {
    if !book.resources.iter().any(|r| r.id == base) {
        return base.to_owned();
    }
    let mut n = 2usize;
    loop {
        let id = format!("{base}-{n}");
        if !book.resources.iter().any(|r| r.id == id) {
            return id;
        }
        n += 1;
    }
}

fn unique_spine_id(book: &Book) -> String {
    let mut n = book.spine.len();
    loop {
        let id = format!("spine-{n}");
        if !book.spine.iter().any(|s| s.id == id) {
            return id;
        }
        n += 1;
    }
}

/// Where in the top-level nav a new chapter at spine position `spine_pos`
/// (already inserted) should go: right after the nav entry of the closest
/// preceding spine resource that has one, else right before the closest
/// following one, else at the end.
fn nav_insert_index(book: &Book, spine_pos: usize) -> usize {
    let nav_index_of = |resource_id: &str| -> Option<usize> {
        let path = book
            .resources
            .iter()
            .find(|r| r.id == resource_id)?
            .path
            .as_str();
        book.nav
            .iter()
            .position(|p| p.href.as_deref().map(strip_fragment) == Some(path))
    };
    for item in book.spine[..spine_pos].iter().rev() {
        if let Some(i) = nav_index_of(&item.resource) {
            return i + 1;
        }
    }
    for item in &book.spine[spine_pos + 1..] {
        if let Some(i) = nav_index_of(&item.resource) {
            return i;
        }
    }
    book.nav.len()
}

/// Quick well-formedness scan (quick-xml event walk): UTF-8, balanced and
/// matching tags, parseable markup.
fn xml_well_formed(bytes: &[u8]) -> Result<(), String> {
    let text = std::str::from_utf8(bytes).map_err(|e| format!("not valid UTF-8: {e}"))?;
    let mut reader = Reader::from_str(text);
    let mut depth = 0u64;
    loop {
        match reader.read_event() {
            Ok(XmlEvent::Start(_)) => depth += 1,
            Ok(XmlEvent::End(_)) => match depth.checked_sub(1) {
                Some(d) => depth = d,
                None => return Err("unbalanced closing tag".into()),
            },
            Ok(XmlEvent::Eof) => {
                return if depth == 0 {
                    Ok(())
                } else {
                    Err("unclosed element at end of document".into())
                }
            }
            Ok(_) => {}
            Err(e) => return Err(format!("{e} at byte {}", reader.buffer_position())),
        }
    }
}

/// Fill `Resource.size` from the zip. Manifest items whose entry is missing
/// from the archive keep size 0 (lenient on read; validation flags them).
fn fill_sizes(resources: &mut [Resource], container: &mut OcfContainer<File>) {
    for resource in resources {
        if let Ok(size) = container.entry_size(&resource.path) {
            resource.size = size;
        }
    }
}

/// Prefer the EPUB 3 nav document, fall back to the NCX, else empty.
fn parse_nav(
    container: &mut OcfContainer<File>,
    resources: &[Resource],
    nav_resource: Option<&str>,
    ncx_resource: Option<&str>,
) -> CoreResult<Vec<NavPoint>> {
    let path_of = |id: &str| {
        resources
            .iter()
            .find(|r| r.id == id)
            .map(|r| r.path.clone())
    };
    if let Some(path) = nav_resource.and_then(path_of) {
        let bytes = container.read_entry(&path)?;
        return nav::parse_nav_xhtml(&bytes, &path);
    }
    if let Some(path) = ncx_resource.and_then(path_of) {
        let bytes = container.read_entry(&path)?;
        return nav::parse_ncx(&bytes, &path);
    }
    Ok(Vec::new())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use zip::write::SimpleFileOptions;

    const CONTAINER_XML: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <rootfiles>
    <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>"#;

    const EPUB3_OPF: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="pub-id">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:identifier id="pub-id">urn:uuid:1234</dc:identifier>
    <dc:title>Ünïcode “Book” ✓</dc:title>
    <dc:creator>Author One</dc:creator>
    <dc:language>en</dc:language>
  </metadata>
  <manifest>
    <item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/>
    <item id="ch1" href="ch1.xhtml" media-type="application/xhtml+xml"/>
    <item id="ch2" href="ch2.xhtml" media-type="application/xhtml+xml"/>
    <item id="style" href="style.css" media-type="text/css"/>
  </manifest>
  <spine>
    <itemref idref="ch1"/>
    <itemref idref="ch2"/>
  </spine>
</package>"#;

    const NAV_XHTML: &str = r#"<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
<body><nav epub:type="toc"><ol>
  <li><a href="ch1.xhtml">Chapter 1</a></li>
  <li><a href="ch2.xhtml">Chapter 2</a></li>
</ol></nav></body></html>"#;

    const CH1: &str = r#"<html xmlns="http://www.w3.org/1999/xhtml"><body><p>Hëllo — chapter one ✓</p></body></html>"#;
    const CH2: &str =
        r#"<html xmlns="http://www.w3.org/1999/xhtml"><body><p>Chapter two</p></body></html>"#;
    const CSS: &str = "body { color: black; }";

    const EPUB2_OPF: &str = r#"<?xml version="1.0"?>
<package xmlns="http://www.idpf.org/2007/opf" version="2.0" unique-identifier="bookid">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:title>Old Book</dc:title>
    <dc:language>de</dc:language>
    <dc:identifier id="bookid">isbn:12345</dc:identifier>
  </metadata>
  <manifest>
    <item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>
    <item id="ch1" href="ch1.xhtml" media-type="application/xhtml+xml"/>
  </manifest>
  <spine toc="ncx">
    <itemref idref="ch1"/>
  </spine>
</package>"#;

    const NCX: &str = r#"<?xml version="1.0"?>
<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1">
  <navMap>
    <navPoint id="n1" playOrder="1">
      <navLabel><text>Kapitel 1</text></navLabel>
      <content src="ch1.xhtml"/>
    </navPoint>
  </navMap>
</ncx>"#;

    /// Write a real .epub (zip) file into a per-test temp dir.
    fn write_epub(name: &str, entries: &[(&str, &str)]) -> std::path::PathBuf {
        let dir =
            std::env::temp_dir().join(format!("epubzilla-session-tests-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join(name);
        let file = std::fs::File::create(&path).unwrap();
        let mut writer = zip::ZipWriter::new(file);
        for (entry, content) in entries {
            let options = if *entry == "mimetype" {
                SimpleFileOptions::default().compression_method(zip::CompressionMethod::Stored)
            } else {
                SimpleFileOptions::default()
            };
            writer.start_file(*entry, options).unwrap();
            writer.write_all(content.as_bytes()).unwrap();
        }
        writer.finish().unwrap();
        path
    }

    fn epub3_entries() -> Vec<(&'static str, &'static str)> {
        vec![
            ("mimetype", "application/epub+zip"),
            ("META-INF/container.xml", CONTAINER_XML),
            ("OEBPS/content.opf", EPUB3_OPF),
            ("OEBPS/nav.xhtml", NAV_XHTML),
            ("OEBPS/ch1.xhtml", CH1),
            ("OEBPS/ch2.xhtml", CH2),
            ("OEBPS/style.css", CSS),
        ]
    }

    #[test]
    fn opens_epub3_end_to_end() {
        let path = write_epub("epub3.epub", &epub3_entries());
        let mut session = Session::new();
        let book = session.open_book(&path).unwrap();

        assert_eq!(book.metadata.title, "Ünïcode “Book” ✓");
        assert_eq!(book.metadata.authors, vec!["Author One"]);
        assert_eq!(book.epub_version, crate::EpubVersion::V3);
        assert_eq!(book.source.as_deref(), Some(path.to_str().unwrap()));
        assert!(!book.dirty);

        assert_eq!(book.spine.len(), 2);
        assert_eq!(book.spine[0].resource, "ch1");

        assert_eq!(book.nav.len(), 2);
        assert_eq!(book.nav[0].label, "Chapter 1");
        assert_eq!(book.nav[0].href.as_deref(), Some("OEBPS/ch1.xhtml"));

        // Sizes are filled from the archive.
        let ch1 = book.resources.iter().find(|r| r.id == "ch1").unwrap();
        assert_eq!(ch1.size, CH1.len() as u64);
        assert!(book.resources.iter().all(|r| r.size > 0));

        // get_book returns the same snapshot.
        let again = session.get_book(&book.id).unwrap();
        assert_eq!(again.metadata.title, book.metadata.title);
    }

    #[test]
    fn opens_epub2_with_ncx_fallback() {
        let entries = vec![
            ("mimetype", "application/epub+zip"),
            ("META-INF/container.xml", CONTAINER_XML),
            ("OEBPS/content.opf", EPUB2_OPF),
            ("OEBPS/toc.ncx", NCX),
            ("OEBPS/ch1.xhtml", CH1),
        ];
        let path = write_epub("epub2.epub", &entries);
        let mut session = Session::new();
        let book = session.open_book(&path).unwrap();

        assert_eq!(book.epub_version, crate::EpubVersion::V2);
        assert_eq!(book.metadata.title, "Old Book");
        assert_eq!(book.nav.len(), 1);
        assert_eq!(book.nav[0].label, "Kapitel 1");
        assert_eq!(book.nav[0].href.as_deref(), Some("OEBPS/ch1.xhtml"));
    }

    #[test]
    fn reads_chapter_lazily() {
        let path = write_epub("lazy.epub", &epub3_entries());
        let mut session = Session::new();
        let book = session.open_book(&path).unwrap();

        let chapter = session
            .read_chapter(&book.id, "ch1", ContentFormat::Xhtml)
            .unwrap();
        assert_eq!(chapter.resource, "ch1");
        assert_eq!(chapter.format, ContentFormat::Xhtml);
        assert_eq!(chapter.content, CH1);

        // prefer: Markdown converts in-subset bodies (M0.8).
        let chapter = session
            .read_chapter(&book.id, "ch2", ContentFormat::Markdown)
            .unwrap();
        assert_eq!(chapter.format, ContentFormat::Markdown);
        assert_eq!(chapter.content, "Chapter two\n");
    }

    #[test]
    fn read_chapter_rejects_non_xhtml() {
        let path = write_epub("nonxhtml.epub", &epub3_entries());
        let mut session = Session::new();
        let book = session.open_book(&path).unwrap();
        let err = session
            .read_chapter(&book.id, "style", ContentFormat::Xhtml)
            .unwrap_err();
        assert!(matches!(err, CoreError::UnsupportedFeature { .. }));
    }

    #[test]
    fn reads_any_resource() {
        let path = write_epub("resource.epub", &epub3_entries());
        let mut session = Session::new();
        let book = session.open_book(&path).unwrap();
        let bytes = session.read_resource(&book.id, "style").unwrap();
        assert_eq!(bytes, CSS.as_bytes());
    }

    #[test]
    fn unknown_ids_are_not_found() {
        let path = write_epub("unknown.epub", &epub3_entries());
        let mut session = Session::new();
        let book = session.open_book(&path).unwrap();

        let err = session.get_book("book-999").unwrap_err();
        assert!(matches!(err, CoreError::ResourceNotFound { id } if id == "book-999"));

        let err = session
            .read_chapter(&book.id, "nope", ContentFormat::Xhtml)
            .unwrap_err();
        assert!(matches!(err, CoreError::ResourceNotFound { id } if id == "nope"));

        let err = session.read_resource("book-999", "ch1").unwrap_err();
        assert!(matches!(err, CoreError::ResourceNotFound { .. }));
    }

    #[test]
    fn close_book_drops_state() {
        let path = write_epub("close.epub", &epub3_entries());
        let mut session = Session::new();
        let book = session.open_book(&path).unwrap();

        session.close_book(&book.id).unwrap();
        assert!(matches!(
            session.get_book(&book.id),
            Err(CoreError::ResourceNotFound { .. })
        ));
        assert!(matches!(
            session.close_book(&book.id),
            Err(CoreError::ResourceNotFound { .. })
        ));
    }

    #[test]
    fn book_ids_are_unique() {
        let path = write_epub("ids.epub", &epub3_entries());
        let mut session = Session::new();
        let a = session.open_book(&path).unwrap();
        let b = session.open_book(&path).unwrap();
        assert_ne!(a.id, b.id);
    }

    #[test]
    fn dangling_nav_target_is_malformed() {
        let opf = EPUB3_OPF.replace(
            r#"<item id="ch2" href="ch2.xhtml" media-type="application/xhtml+xml"/>"#,
            r#"<item id="ch2" href="ch2.xhtml" media-type="application/xhtml+xml"/><item id="junk" href="junk.xhtml" media-type="application/xhtml+xml"/>"#,
        );
        let nav = NAV_XHTML.replace("ch2.xhtml", "gone.xhtml");
        let entries = vec![
            ("mimetype", "application/epub+zip"),
            ("META-INF/container.xml", CONTAINER_XML),
            ("OEBPS/content.opf", opf.as_str()),
            ("OEBPS/nav.xhtml", nav.as_str()),
            ("OEBPS/ch1.xhtml", CH1),
            ("OEBPS/ch2.xhtml", CH2),
            ("OEBPS/style.css", CSS),
        ];
        let path = write_epub("badnav.epub", &entries);
        let err = Session::new().open_book(&path).unwrap_err();
        assert!(matches!(err, CoreError::MalformedPackage { .. }));
    }

    #[test]
    fn spine_referencing_missing_manifest_item_is_malformed() {
        let opf = EPUB3_OPF.replace(r#"<itemref idref="ch2"/>"#, r#"<itemref idref="ghost"/>"#);
        let entries = vec![
            ("mimetype", "application/epub+zip"),
            ("META-INF/container.xml", CONTAINER_XML),
            ("OEBPS/content.opf", opf.as_str()),
            ("OEBPS/nav.xhtml", NAV_XHTML),
            ("OEBPS/ch1.xhtml", CH1),
            ("OEBPS/ch2.xhtml", CH2),
            ("OEBPS/style.css", CSS),
        ];
        let path = write_epub("badspine.epub", &entries);
        let err = Session::new().open_book(&path).unwrap_err();
        assert!(
            matches!(err, CoreError::MalformedPackage { message } if message.contains("ghost"))
        );
    }

    fn sample_metadata() -> Metadata {
        Metadata {
            title: "Nëw “Bøok” ✓".into(),
            authors: vec!["Ærin Author".into(), "Zoë Writer".into()],
            language: "en".into(),
            identifier: String::new(),
            modified: None,
            description: Some("A tëst description".into()),
            publisher: None,
            cover_resource: None,
        }
    }

    fn temp_path(name: &str) -> std::path::PathBuf {
        let dir =
            std::env::temp_dir().join(format!("epubzilla-session-tests-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        dir.join(name)
    }

    #[test]
    fn create_book_has_consistent_model() {
        let mut session = Session::new();
        let book = session.create_book(sample_metadata());

        assert_eq!(book.source, None);
        assert!(book.dirty);
        assert_eq!(book.epub_version, crate::EpubVersion::V3);
        assert!(book.metadata.identifier.starts_with("urn:uuid:"));

        // Spine → title page, nav lists it, all consistent.
        assert_eq!(book.spine.len(), 1);
        assert_eq!(book.spine[0].resource, "titlepage");
        let titlepage = book.resources.iter().find(|r| r.id == "titlepage").unwrap();
        assert_eq!(titlepage.media_type, XHTML_MEDIA_TYPE);
        assert!(titlepage.size > 0);
        assert!(book.resources.iter().any(|r| r.id == "nav"));
        assert_eq!(book.nav.len(), 1);
        assert_eq!(book.nav[0].href.as_deref(), Some(titlepage.path.as_str()));
        assert_eq!(book.nav[0].label, "Nëw “Bøok” ✓");

        // In-memory chapters are readable through the overlay.
        let mut session2 = session;
        let chapter = session2
            .read_chapter(&book.id, "titlepage", ContentFormat::Xhtml)
            .unwrap();
        assert!(chapter.content.contains("Nëw “Bøok” ✓"));
        assert!(chapter.content.contains("Ærin Author"));
        assert!(chapter.content.contains("Zoë Writer"));
        let nav_doc = String::from_utf8(session2.read_resource(&book.id, "nav").unwrap()).unwrap();
        assert!(nav_doc.contains(r#"epub:type="toc""#));
        assert!(nav_doc.contains(r#"href="titlepage.xhtml""#));
    }

    #[test]
    fn save_as_writes_valid_zip_with_stored_mimetype_first() {
        let mut session = Session::new();
        let book = session.create_book(sample_metadata());
        // Own subdirectory: the leftover-scan below must not race with other
        // tests' in-flight temp files in the shared directory.
        let dir = temp_path("save-as-dir");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("created.epub");
        let saved = session
            .save_book(&book.id, Some(path.to_string_lossy().into_owned()))
            .unwrap();

        assert_eq!(saved.source.as_deref(), Some(path.to_str().unwrap()));
        assert!(!saved.dirty);
        let modified = saved.metadata.modified.as_deref().unwrap();
        assert!(modified.ends_with('Z') && modified.len() == 20);

        // First entry: "mimetype", stored, exact content.
        let file = std::fs::File::open(&path).unwrap();
        let mut archive = zip::ZipArchive::new(file).unwrap();
        {
            let mut first = archive.by_index(0).unwrap();
            assert_eq!(first.name(), "mimetype");
            assert_eq!(first.compression(), zip::CompressionMethod::Stored);
            let mut content = String::new();
            std::io::Read::read_to_string(&mut first, &mut content).unwrap();
            assert_eq!(content, "application/epub+zip");
        }
        // No temp file left behind.
        let leftovers: Vec<_> = std::fs::read_dir(path.parent().unwrap())
            .unwrap()
            .filter_map(|e| e.ok())
            .filter(|e| e.file_name().to_string_lossy().contains(".tmp-"))
            .collect();
        assert!(leftovers.is_empty());
    }

    #[test]
    fn saved_created_book_reopens_cleanly() {
        let mut session = Session::new();
        let created = session.create_book(sample_metadata());
        let path = temp_path("roundtrip.epub");
        let saved = session
            .save_book(&created.id, Some(path.to_string_lossy().into_owned()))
            .unwrap();

        let reopened = session.open_book(&path).unwrap();
        assert_eq!(reopened.metadata.title, created.metadata.title);
        assert_eq!(reopened.metadata.authors, created.metadata.authors);
        assert_eq!(reopened.metadata.language, "en");
        assert_eq!(reopened.metadata.identifier, saved.metadata.identifier);
        assert_eq!(reopened.metadata.modified, saved.metadata.modified);
        assert_eq!(reopened.epub_version, crate::EpubVersion::V3);
        assert_eq!(reopened.spine.len(), 1);
        assert_eq!(reopened.spine[0].resource, "titlepage");
        assert_eq!(reopened.nav.len(), 1);
        assert_eq!(reopened.nav[0].label, created.nav[0].label);
        assert_eq!(reopened.nav[0].href, created.nav[0].href);
        assert_eq!(reopened.resources.len(), created.resources.len());

        let chapter = session
            .read_chapter(&reopened.id, "titlepage", ContentFormat::Xhtml)
            .unwrap();
        assert!(chapter.content.contains("Nëw “Bøok” ✓"));
    }

    #[test]
    fn incremental_save_raw_copies_untouched_entries() {
        let source = write_epub("incremental-src.epub", &epub3_entries());
        let mut session = Session::new();
        let book = session.open_book(&source).unwrap();
        let target = temp_path("incremental-dst.epub");
        session
            .save_book(&book.id, Some(target.to_string_lossy().into_owned()))
            .unwrap();

        // Untouched entries are byte-for-byte identical at the raw
        // (compressed) level: same method, CRC, and stream bytes.
        let raw = |path: &std::path::Path, name: &str| {
            let mut archive = zip::ZipArchive::new(std::fs::File::open(path).unwrap()).unwrap();
            let index = archive.index_for_name(name).unwrap();
            let mut entry = archive.by_index_raw(index).unwrap();
            let mut bytes = Vec::new();
            std::io::Read::read_to_end(&mut entry, &mut bytes).unwrap();
            (entry.compression(), entry.crc32(), bytes)
        };
        for name in [
            "OEBPS/ch1.xhtml",
            "OEBPS/ch2.xhtml",
            "OEBPS/nav.xhtml",
            "OEBPS/style.css",
            "META-INF/container.xml",
        ] {
            assert_eq!(raw(&source, name), raw(&target, name), "entry {name}");
        }

        // The saved book reopens with the same model.
        let reopened = session.open_book(&target).unwrap();
        assert_eq!(reopened.metadata.title, book.metadata.title);
        assert_eq!(reopened.spine.len(), book.spine.len());
        assert_eq!(reopened.nav.len(), book.nav.len());
        // dcterms:modified was refreshed in the regenerated OPF.
        assert!(reopened.metadata.modified.is_some());
    }

    #[test]
    fn save_without_source_and_without_path_is_an_error() {
        let mut session = Session::new();
        let book = session.create_book(sample_metadata());
        let err = session.save_book(&book.id, None).unwrap_err();
        assert!(matches!(err, CoreError::Io { message } if message.contains("path is required")));
        // Book state untouched by the failed save.
        let book = session.get_book(&book.id).unwrap();
        assert!(book.dirty);
        assert_eq!(book.source, None);
    }

    #[test]
    fn failed_save_leaves_no_partial_file() {
        let mut session = Session::new();
        let book = session.create_book(sample_metadata());
        let missing_dir = temp_path("no-such-dir");
        let target = missing_dir.join("out.epub");
        let err = session
            .save_book(&book.id, Some(target.to_string_lossy().into_owned()))
            .unwrap_err();
        assert!(matches!(err, CoreError::Io { .. }));
        assert!(!target.exists());
        assert!(!missing_dir.exists());
        // Still unsaved and dirty.
        let book = session.get_book(&book.id).unwrap();
        assert!(book.dirty);
        assert_eq!(book.source, None);
    }

    #[test]
    fn save_without_path_reuses_source() {
        let source = write_epub("resave-src.epub", &epub3_entries());
        // Copy so we don't clobber the shared fixture used by other tests.
        let target = temp_path("resave-copy.epub");
        std::fs::copy(&source, &target).unwrap();
        let mut session = Session::new();
        let book = session.open_book(&target).unwrap();
        let saved = session.save_book(&book.id, None).unwrap();
        assert_eq!(saved.source.as_deref(), Some(target.to_str().unwrap()));
        assert!(!saved.dirty);
        // Target still opens cleanly after in-place save.
        session.open_book(&target).unwrap();
    }

    /// Consistency invariants (domain-model.md): every spine resource and
    /// nav target resolves in the manifest; manifest ids/paths are unique.
    fn assert_consistent(book: &Book) {
        for item in &book.spine {
            assert!(
                book.resources.iter().any(|r| r.id == item.resource),
                "spine item {:?} dangles",
                item.id
            );
        }
        fn check_nav(nav: &[NavPoint], resources: &[Resource]) {
            for point in nav {
                if let Some(href) = &point.href {
                    let path = strip_fragment(href);
                    assert!(
                        resources.iter().any(|r| r.path == path),
                        "nav entry {:?} dangles: {href}",
                        point.label
                    );
                }
                check_nav(&point.children, resources);
            }
        }
        check_nav(&book.nav, &book.resources);
        let mut ids = std::collections::HashSet::new();
        let mut paths = std::collections::HashSet::new();
        for r in &book.resources {
            assert!(ids.insert(&r.id), "duplicate manifest id {:?}", r.id);
            assert!(
                paths.insert(&r.path),
                "duplicate manifest path {:?}",
                r.path
            );
        }
    }

    fn md_chapter(resource: &str, content: &str) -> ChapterContent {
        ChapterContent {
            resource: resource.to_owned(),
            format: ContentFormat::Markdown,
            content: content.to_owned(),
        }
    }

    /// A tiny valid 1x1 PNG; the core never decodes image bytes.
    const PNG_1X1: &[u8] = &[
        0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44,
        0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x06, 0x00, 0x00, 0x00, 0x1F,
        0x15, 0xC4, 0x89, 0x00, 0x00, 0x00, 0x0A, 0x49, 0x44, 0x41, 0x54, 0x78, 0x9C, 0x63, 0x00,
        0x01, 0x00, 0x00, 0x05, 0x00, 0x01, 0x0D, 0x0A, 0x2D, 0xB4, 0x00, 0x00, 0x00, 0x00, 0x49,
        0x45, 0x4E, 0x44, 0xAE, 0x42, 0x60, 0x82,
    ];

    #[test]
    fn add_resource_stores_bytes_under_images_and_sets_dirty() {
        let mut session = Session::new();
        let book = session.create_book(sample_metadata());
        let book = session
            .add_resource(
                &book.id,
                "/photos/Mÿ Pïc (1).PNG",
                "image/png",
                PNG_1X1.to_vec(),
            )
            .unwrap();

        assert!(book.dirty);
        assert_consistent(&book);
        // Sanitized stem, lowercased extension, under <pkg dir>/images/.
        let added = book
            .resources
            .iter()
            .find(|r| r.path.starts_with("OEBPS/images/"))
            .unwrap();
        assert_eq!(added.path, "OEBPS/images/Mÿ-Pïc-1.png");
        assert_eq!(added.id, "Mÿ-Pïc-1");
        assert_eq!(added.media_type, "image/png");
        assert_eq!(added.size, PNG_1X1.len() as u64);
        // The overlay serves the bytes immediately.
        let bytes = session.read_resource(&book.id, &added.id).unwrap();
        assert_eq!(bytes, PNG_1X1);
    }

    #[test]
    fn add_resource_resolves_collisions_with_numeric_suffixes() {
        let mut session = Session::new();
        let book = session.create_book(sample_metadata());
        let book = session
            .add_resource(&book.id, "foo.png", "image/png", PNG_1X1.to_vec())
            .unwrap();
        let book = session
            .add_resource(&book.id, "some/dir/foo.png", "image/png", vec![1, 2, 3])
            .unwrap();
        let book = session
            .add_resource(&book.id, "foo.png", "image/png", vec![4])
            .unwrap();

        assert_consistent(&book);
        let paths: Vec<&str> = book
            .resources
            .iter()
            .filter(|r| r.path.starts_with("OEBPS/images/"))
            .map(|r| r.path.as_str())
            .collect();
        assert_eq!(
            paths,
            vec![
                "OEBPS/images/foo.png",
                "OEBPS/images/foo-2.png",
                "OEBPS/images/foo-3.png"
            ]
        );
        // Each entry serves its own bytes.
        assert_eq!(
            session.read_resource(&book.id, "foo-2").unwrap(),
            vec![1, 2, 3]
        );
        assert_eq!(session.read_resource(&book.id, "foo-3").unwrap(), vec![4]);
    }

    #[test]
    fn add_resource_rejects_epub2() {
        let entries = vec![
            ("mimetype", "application/epub+zip"),
            ("META-INF/container.xml", CONTAINER_XML),
            ("OEBPS/content.opf", EPUB2_OPF),
            ("OEBPS/toc.ncx", NCX),
            ("OEBPS/ch1.xhtml", CH1),
        ];
        let path = write_epub("addres-epub2.epub", &entries);
        let mut session = Session::new();
        let book = session.open_book(&path).unwrap();
        let err = session
            .add_resource(&book.id, "foo.png", "image/png", PNG_1X1.to_vec())
            .unwrap_err();
        assert!(matches!(err, CoreError::UnsupportedFeature { .. }));
    }

    #[test]
    fn added_resource_survives_save_and_reopen() {
        let mut session = Session::new();
        let book = session.create_book(sample_metadata());
        let book = session
            .add_resource(&book.id, "pïxel.png", "image/png", PNG_1X1.to_vec())
            .unwrap();
        let path = temp_path("addres-roundtrip.epub");
        session
            .save_book(&book.id, Some(path.to_string_lossy().into_owned()))
            .unwrap();

        let reopened = session.open_book(&path).unwrap();
        let added = reopened
            .resources
            .iter()
            .find(|r| r.path == "OEBPS/images/pïxel.png")
            .unwrap();
        assert_eq!(added.media_type, "image/png");
        assert_eq!(added.size, PNG_1X1.len() as u64);
        let bytes = session.read_resource(&reopened.id, &added.id).unwrap();
        assert_eq!(bytes, PNG_1X1);
    }

    #[test]
    fn add_resource_hint_edge_cases() {
        // Pure-helper checks: extension-less and hostile hints stay usable.
        assert_eq!(split_hint("foo.PNG"), ("foo".into(), Some("png".into())));
        assert_eq!(
            split_hint("C:\\pics\\a b.jpeg"),
            ("a b".into(), Some("jpeg".into()))
        );
        assert_eq!(split_hint("noext"), ("noext".into(), None));
        assert_eq!(split_hint(".hidden"), (".hidden".into(), None));
        assert_eq!(sanitize_stem("Mÿ Pïc (1)"), "Mÿ-Pïc-1");
        assert_eq!(sanitize_stem("///"), "resource");
        assert_eq!(sanitize_stem("__ok__"), "__ok__");
    }

    #[test]
    fn add_chapter_wires_manifest_spine_and_nav() {
        let mut session = Session::new();
        let book = session.create_book(sample_metadata());
        let book = session
            .add_chapter(&book.id, "Chäpter Öne ✓", None)
            .unwrap();

        assert!(book.dirty);
        assert_consistent(&book);
        assert_eq!(book.spine.len(), 2);
        let item = &book.spine[1];
        let resource = book
            .resources
            .iter()
            .find(|r| r.id == item.resource)
            .unwrap();
        assert_eq!(resource.media_type, XHTML_MEDIA_TYPE);
        assert!(resource.size > 0);
        // Nav entry sits after the title page, consistent with the spine.
        assert_eq!(book.nav.len(), 2);
        assert_eq!(book.nav[1].label, "Chäpter Öne ✓");
        assert_eq!(book.nav[1].href.as_deref(), Some(resource.path.as_str()));

        // The chapter document is a valid frame with the title.
        let chapter = session
            .read_chapter(&book.id, &item.resource, ContentFormat::Xhtml)
            .unwrap();
        assert!(chapter.content.contains("<title>Chäpter Öne ✓</title>"));
        assert!(chapter.content.contains("<h1>Chäpter Öne ✓</h1>"));
    }

    #[test]
    fn add_chapter_after_positions_spine_and_nav() {
        let mut session = Session::new();
        let book = session.create_book(sample_metadata());
        let book = session.add_chapter(&book.id, "One", None).unwrap();
        let book = session.add_chapter(&book.id, "Three", None).unwrap();
        // Insert between them.
        let after = book.spine[1].id.clone();
        let book = session.add_chapter(&book.id, "Two", Some(&after)).unwrap();

        assert_consistent(&book);
        let labels: Vec<&str> = book.nav.iter().map(|p| p.label.as_str()).collect();
        assert_eq!(labels[1..], ["One", "Two", "Three"]);
        let spine_paths: Vec<&str> = book.spine[1..]
            .iter()
            .map(|s| {
                book.resources
                    .iter()
                    .find(|r| r.id == s.resource)
                    .unwrap()
                    .path
                    .as_str()
            })
            .collect();
        let nav_paths: Vec<&str> = book.nav[1..]
            .iter()
            .map(|p| p.href.as_deref().unwrap())
            .collect();
        assert_eq!(spine_paths, nav_paths);

        let err = session
            .add_chapter(&book.id, "Nope", Some("spine-404"))
            .unwrap_err();
        assert!(matches!(err, CoreError::ResourceNotFound { id } if id == "spine-404"));
    }

    #[test]
    fn write_chapter_markdown_roundtrips_and_preserves_head() {
        let mut session = Session::new();
        let book = session.create_book(sample_metadata());
        let book = session.add_chapter(&book.id, "Chapter Ünï", None).unwrap();
        let resource_id = book.spine[1].resource.clone();

        let md = "# Chapter Ünï\n\nSome *emphasized* tëxt ✓.\n\n- one\n- two\n";
        let book = session
            .write_chapter(&book.id, &resource_id, md_chapter(&resource_id, md))
            .unwrap();
        assert!(book.dirty);
        assert_consistent(&book);
        let size = book
            .resources
            .iter()
            .find(|r| r.id == resource_id)
            .unwrap()
            .size;

        // Stored form: XHTML with the original frame (head/title) preserved.
        let stored = session
            .read_chapter(&book.id, &resource_id, ContentFormat::Xhtml)
            .unwrap();
        assert_eq!(stored.format, ContentFormat::Xhtml);
        assert!(stored.content.contains("<title>Chapter Ünï</title>"));
        assert!(stored.content.contains("<em>emphasized</em>"));
        assert_eq!(stored.content.len() as u64, size);

        // Read back as Markdown: the round-trip is clean.
        let back = session
            .read_chapter(&book.id, &resource_id, ContentFormat::Markdown)
            .unwrap();
        assert_eq!(back.format, ContentFormat::Markdown);
        assert_eq!(back.content, md);
    }

    #[test]
    fn read_chapter_markdown_falls_back_to_xhtml_when_lossy() {
        let mut session = Session::new();
        let book = session.create_book(sample_metadata());
        let book = session.add_chapter(&book.id, "Styled", None).unwrap();
        let resource_id = book.spine[1].resource.clone();

        let doc = r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head><title>Styled</title></head>
<body><p style="color: red">Oût of subset ✓</p></body>
</html>
"#;
        session
            .write_chapter(
                &book.id,
                &resource_id,
                ChapterContent {
                    resource: resource_id.clone(),
                    format: ContentFormat::Xhtml,
                    content: doc.to_owned(),
                },
            )
            .unwrap();

        let chapter = session
            .read_chapter(&book.id, &resource_id, ContentFormat::Markdown)
            .unwrap();
        assert_eq!(chapter.format, ContentFormat::Xhtml);
        assert_eq!(chapter.content, doc);
    }

    #[test]
    fn update_metadata_regenerates_generated_title_page() {
        let mut session = Session::new();
        let book = session.create_book(sample_metadata());
        let mut metadata = sample_metadata();
        metadata.title = "Renämed ✓".into();
        metadata.identifier = book.metadata.identifier.clone();
        let book = session.update_metadata(&book.id, metadata).unwrap();

        assert!(book.dirty);
        assert_consistent(&book);
        assert_eq!(book.metadata.title, "Renämed ✓");
        assert_eq!(book.nav[0].label, "Renämed ✓");
        let page = session
            .read_chapter(&book.id, "titlepage", ContentFormat::Xhtml)
            .unwrap();
        assert!(page.content.contains("<h1>Renämed ✓</h1>"));
        let nav_doc = String::from_utf8(session.read_resource(&book.id, "nav").unwrap()).unwrap();
        assert!(nav_doc.contains("Renämed ✓"));
    }

    #[test]
    fn remove_chapter_cleans_spine_nav_manifest_and_overlay() {
        let mut session = Session::new();
        let book = session.create_book(sample_metadata());
        let book = session.add_chapter(&book.id, "Keep", None).unwrap();
        let book = session.add_chapter(&book.id, "Drop", None).unwrap();
        let drop_item = book.spine[2].id.clone();
        let drop_resource = book.spine[2].resource.clone();
        let drop_path = book
            .resources
            .iter()
            .find(|r| r.id == drop_resource)
            .unwrap()
            .path
            .clone();

        let book = session.remove_chapter(&book.id, &drop_item).unwrap();
        assert!(book.dirty);
        assert_consistent(&book);
        assert_eq!(book.spine.len(), 2);
        assert!(!book.spine.iter().any(|s| s.id == drop_item));
        assert!(!book.resources.iter().any(|r| r.id == drop_resource));
        assert!(!nav_references(&book.nav, &drop_path));
        // Bytes are gone from the session too.
        assert!(matches!(
            session.read_resource(&book.id, &drop_resource),
            Err(CoreError::ResourceNotFound { .. })
        ));
        // The regenerated nav document no longer mentions it.
        let nav_doc = String::from_utf8(session.read_resource(&book.id, "nav").unwrap()).unwrap();
        assert!(!nav_doc.contains("Drop"));
        assert!(nav_doc.contains("Keep"));

        let err = session.remove_chapter(&book.id, &drop_item).unwrap_err();
        assert!(matches!(err, CoreError::ResourceNotFound { .. }));
    }

    #[test]
    fn remove_chapter_excludes_entry_from_saved_zip() {
        let source = write_epub("remove-src.epub", &epub3_entries());
        let mut session = Session::new();
        let book = session.open_book(&source).unwrap();
        let item = book.spine[1].id.clone(); // ch2
        session.remove_chapter(&book.id, &item).unwrap();

        let target = temp_path("remove-dst.epub");
        session
            .save_book(&book.id, Some(target.to_string_lossy().into_owned()))
            .unwrap();
        let archive = zip::ZipArchive::new(std::fs::File::open(&target).unwrap()).unwrap();
        let names: Vec<&str> = archive.file_names().collect();
        assert!(!names.contains(&"OEBPS/ch2.xhtml"), "names: {names:?}");
        assert!(names.contains(&"OEBPS/ch1.xhtml"));

        let reopened = session.open_book(&target).unwrap();
        assert_eq!(reopened.spine.len(), 1);
        assert!(!nav_references(&reopened.nav, "OEBPS/ch2.xhtml"));
    }

    #[test]
    fn reorder_spine_reorders_nav_to_match() {
        let mut session = Session::new();
        let book = session.create_book(sample_metadata());
        let book = session.add_chapter(&book.id, "One", None).unwrap();
        let book = session.add_chapter(&book.id, "Two", None).unwrap();
        let book = session.add_chapter(&book.id, "Three", None).unwrap();

        let order: Vec<SpineItemId> = vec![
            book.spine[0].id.clone(), // titlepage stays first
            book.spine[3].id.clone(),
            book.spine[1].id.clone(),
            book.spine[2].id.clone(),
        ];
        let book = session.reorder_spine(&book.id, &order).unwrap();
        assert!(book.dirty);
        assert_consistent(&book);
        let ids: Vec<&str> = book.spine.iter().map(|s| s.id.as_str()).collect();
        assert_eq!(ids, order.iter().map(String::as_str).collect::<Vec<_>>());
        let labels: Vec<&str> = book.nav.iter().map(|p| p.label.as_str()).collect();
        assert_eq!(labels[1..], ["Three", "One", "Two"]);
    }

    #[test]
    fn reorder_spine_rejects_non_permutations() {
        let mut session = Session::new();
        let book = session.create_book(sample_metadata());
        let book = session.add_chapter(&book.id, "One", None).unwrap();
        let a = book.spine[0].id.clone();
        let b = book.spine[1].id.clone();

        for bad in [
            vec![a.clone()],                         // too short
            vec![a.clone(), b.clone(), a.clone()],   // too long
            vec![a.clone(), "spine-404".to_owned()], // unknown id
            vec![a.clone(), a.clone()],              // duplicate
        ] {
            let err = session.reorder_spine(&book.id, &bad).unwrap_err();
            assert!(
                matches!(err, CoreError::MalformedPackage { .. }),
                "expected MalformedPackage for {bad:?}"
            );
        }
        // Book untouched by the failed reorders.
        let book = session.get_book(&book.id).unwrap();
        assert_eq!(book.spine[0].id, a);
        assert_eq!(book.spine[1].id, b);
    }

    #[test]
    fn mutations_reject_epub2_books() {
        let entries = vec![
            ("mimetype", "application/epub+zip"),
            ("META-INF/container.xml", CONTAINER_XML),
            ("OEBPS/content.opf", EPUB2_OPF),
            ("OEBPS/toc.ncx", NCX),
            ("OEBPS/ch1.xhtml", CH1),
        ];
        let path = write_epub("readonly.epub", &entries);
        let mut session = Session::new();
        let book = session.open_book(&path).unwrap();
        let err = session.add_chapter(&book.id, "Nope", None).unwrap_err();
        assert!(matches!(err, CoreError::UnsupportedFeature { .. }));
    }

    #[test]
    fn validate_passes_a_clean_book_and_catches_breakage() {
        let mut session = Session::new();
        let book = session.create_book(sample_metadata());
        let book = session.add_chapter(&book.id, "One", None).unwrap();
        assert!(session.validate(&book.id).unwrap().is_empty());

        // Missing title.
        let mut metadata = sample_metadata();
        metadata.title = String::new();
        session.update_metadata(&book.id, metadata).unwrap();
        let issues = session.validate(&book.id).unwrap();
        assert!(issues
            .iter()
            .any(|i| i.severity == Severity::Error && i.message.contains("dc:title")));
        session
            .update_metadata(&book.id, sample_metadata())
            .unwrap();

        // Dangling spine ref (invariant broken behind the API's back).
        let open = session.books.get_mut(&book.id).unwrap();
        open.book.spine.push(SpineItem {
            id: "spine-bad".into(),
            resource: "ghost".into(),
            linear: true,
        });
        let issues = session.validate(&book.id).unwrap();
        assert!(issues.iter().any(|i| i.message.contains("ghost")));
        let open = session.books.get_mut(&book.id).unwrap();
        open.book.spine.pop();

        // Malformed XHTML bytes.
        let path = open
            .book
            .resources
            .iter()
            .find(|r| r.id == open.book.spine[1].resource)
            .unwrap()
            .path
            .clone();
        let good = open
            .overlay
            .insert(path.clone(), b"<html><p>oops</html>".to_vec());
        let issues = session.validate(&book.id).unwrap();
        assert!(issues
            .iter()
            .any(|i| i.message.contains("not well-formed XML")));
        let open = session.books.get_mut(&book.id).unwrap();
        open.overlay.insert(path.clone(), good.unwrap());

        // Missing resource bytes.
        session
            .books
            .get_mut(&book.id)
            .unwrap()
            .overlay
            .remove(&path);
        let issues = session.validate(&book.id).unwrap();
        assert!(issues.iter().any(|i| i.message.contains("no bytes")));

        // Dangling nav target.
        let open = session.books.get_mut(&book.id).unwrap();
        open.book.nav.push(NavPoint {
            label: "Gone".into(),
            href: Some("OEBPS/gone.xhtml".into()),
            children: Vec::new(),
        });
        let issues = session.validate(&book.id).unwrap();
        assert!(issues
            .iter()
            .any(|i| i.message.contains("not in the manifest")));

        // Duplicate manifest ids.
        let open = session.books.get_mut(&book.id).unwrap();
        let dup = open.book.resources[0].clone();
        open.book.resources.push(dup);
        let issues = session.validate(&book.id).unwrap();
        assert!(issues
            .iter()
            .any(|i| i.message.contains("duplicate manifest id")));
    }

    #[test]
    fn full_mutation_lifecycle_saves_and_reopens_clean() {
        let mut session = Session::new();
        let book = session.create_book(sample_metadata());
        let book_id = book.id.clone();

        // Add three chapters, write Markdown into each.
        let mut chapter_resources = Vec::new();
        for title in ["Ünó", "Dos ✓", "Trés"] {
            let book = session.add_chapter(&book_id, title, None).unwrap();
            chapter_resources.push(book.spine.last().unwrap().resource.clone());
        }
        for (n, resource) in chapter_resources.iter().enumerate() {
            let md = format!("# Chapter {n}\n\nBödy of chapter {n} with *émphasis* ✓.\n");
            session
                .write_chapter(&book_id, resource, md_chapter(resource, &md))
                .unwrap();
        }

        // Reorder: titlepage, Trés, Ünó, Dos ✓.
        let book = session.get_book(&book_id).unwrap();
        let order: Vec<SpineItemId> = vec![
            book.spine[0].id.clone(),
            book.spine[3].id.clone(),
            book.spine[1].id.clone(),
            book.spine[2].id.clone(),
        ];
        session.reorder_spine(&book_id, &order).unwrap();

        // Remove "Dos ✓" (now last).
        let book = session.get_book(&book_id).unwrap();
        let last = book.spine.last().unwrap().id.clone();
        let book = session.remove_chapter(&book_id, &last).unwrap();
        assert_consistent(&book);
        assert!(session.validate(&book_id).unwrap().is_empty());

        // Save, reopen, assert everything survived.
        let path = temp_path("lifecycle.epub");
        session
            .save_book(&book_id, Some(path.to_string_lossy().into_owned()))
            .unwrap();
        let reopened = session.open_book(&path).unwrap();
        assert_consistent(&reopened);
        assert!(!reopened.dirty);
        assert_eq!(reopened.spine.len(), 3);
        let labels: Vec<&str> = reopened.nav.iter().map(|p| p.label.as_str()).collect();
        assert_eq!(labels, ["Nëw “Bøok” ✓", "Trés", "Ünó"]);
        // Spine order: titlepage, Trés (chapter 2), Ünó (chapter 0).
        let spine_paths: Vec<&str> = reopened.spine[1..]
            .iter()
            .map(|s| {
                reopened
                    .resources
                    .iter()
                    .find(|r| r.id == s.resource)
                    .unwrap()
                    .path
                    .as_str()
            })
            .collect();
        let nav_paths: Vec<&str> = reopened.nav[1..]
            .iter()
            .map(|p| p.href.as_deref().unwrap())
            .collect();
        assert_eq!(spine_paths, nav_paths);

        // Chapter content round-trips through the saved file.
        let resource = reopened.spine[2].resource.clone();
        let back = session
            .read_chapter(&reopened.id, &resource, ContentFormat::Markdown)
            .unwrap();
        assert_eq!(back.format, ContentFormat::Markdown);
        assert_eq!(
            back.content,
            "# Chapter 0\n\nBödy of chapter 0 with *émphasis* ✓.\n"
        );

        // The saved file validates with zero findings.
        assert!(session.validate(&reopened.id).unwrap().is_empty());
    }

    #[test]
    fn no_nav_and_no_ncx_gives_empty_nav() {
        let opf = r#"<?xml version="1.0"?>
<package xmlns="http://www.idpf.org/2007/opf" version="3.0">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:title>Bare</dc:title></metadata>
  <manifest><item id="ch1" href="ch1.xhtml" media-type="application/xhtml+xml"/></manifest>
  <spine><itemref idref="ch1"/></spine>
</package>"#;
        let entries = vec![
            ("mimetype", "application/epub+zip"),
            ("META-INF/container.xml", CONTAINER_XML),
            ("OEBPS/content.opf", opf),
            ("OEBPS/ch1.xhtml", CH1),
        ];
        let path = write_epub("nonav.epub", &entries);
        let book = Session::new().open_book(&path).unwrap();
        assert!(book.nav.is_empty());
    }
}
